name: Build and deploy Node.js app to Azure Web App - Secure-Notes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18" # use LTS; Azure runtimes are aligned here
          cache: "npm"

      # Build the React client at the repo root
      - name: Install root and build client
        run: |
          npm install
          npm run build

      # (Optional) quick sanity check that dist exists
      - name: List client dist
        run: |
          ls -la client || true
          ls -la client/dist || true

      # Create a lean artifact (exclude node_modules to reduce size)
      - name: Prepare deployment artifact
        run: |
          mkdir -p artifact
          rsync -a --exclude=node_modules ./ ./artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_886000035F414433948B33887F6BD51B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C15E056354D3418EB4E88889BB88E31D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4E596E9B0FA4C35AD9A77E92D86D98B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Secure-Notes" # must match your App Service name exactly
          slot-name: "Production"
          package: .
